create table student(sno number(3) primary key,sname varchar2(15), course varchar2(10), mark1 number(3),mark2 number(3), result varchar2(4)); 
desc student;
insert into student values(1,'Robert','IIBSC',50,60,'pass'); 
insert into student(sno,sname,course,mark1,mark2) values (2,'Jim','IIBSC',30,60);
insert into student(sno,sname,course,mark1,mark2) values (3,'David','IIIBSC',70,60);
insert into student(sno,sname,course,mark1,mark2) values (4,'Joe','IIIBSC',80,55);
insert into student(sno,sname,course,mark1,mark2) values (5,'Williams','IIBSC',60,50);
insert into student(sno,sname,course,mark1,mark2) values (6,'John','IIBSC',40,30);
insert into student(sno,sname,course,mark1,mark2)  values (7,'Anjel','IIBSC',60,25);
insert into student(sno,sname,course,mark1,mark2) values (8,'Roselin','IIBSC',60,50);
select * from student;
update student set result='pass';
update student set result='fail' where mark1<40 or mark2<40;
select * from student;
delete from student where sno=2;
select * from student;
select * from student where result='pass';
select sno, sname, result from student where course='IIBSC';
truncate table student;
rollback;
drop table student;