create table product(pno number(3), pname varchar2(10), price number(4,1));
insert into product values(1,'pen',10);
insert into product values(2,'pencil',5);
insert into product values(3,'notebook',45);
select * from product;
insert into product values(4,'paper',30);
select * from product;
commit;
select * from product;
insert into product values(5,'shampoo',100);
select * from product;
rollback;
select * from product;
insert into product values(5,'ink',50);
savepoint ss;
insert into product values(6,'soap',60);
select * from product;
rollback to ss;
select * from product;
delete price from product;